spring.application.name=fastcash

# ==============================================================
#  OPCIÓN A: MODO PRODUCCIÓN (RAILWAY HOBBY)
#  (Descomentar este bloque entero al subir a Railway)
# ==============================================================
# OJO: Se añade currentSchema=cliente2 para cuando leas la variable de entorno
# ---> CORRECCIÓN AQUÍ: Se agregó "jdbc:" antes de la variable <---
spring.datasource.url=jdbc:${DATABASE_URL}?currentSchema=cliente2
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

fastcash.security.enabled=true

# SSL OBLIGATORIO PARA RAILWAY
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.sslfactory=org.postgresql.ssl.NonValidatingFactory

# ==============================================================
#  OPCIÓN B: MODO PRUEBAS LOCALES (TU PC)
#  (Descomentar este bloque y COMENTAR la OPCIÓN A para probar)
# ==============================================================
# ---> URL ACTUALIZADA CON EL NUEVO ESQUEMA <---
#spring.datasource.url=jdbc:postgresql://localhost:5432/DvPrueba?currentSchema=cliente2
#spring.datasource.username=postgres
#spring.datasource.password=ansu22
#spring.datasource.driver-class-name=org.postgresql.Driver

# @SuppressWarnings("unknown-property")
#fastcash.security.enabled=false
# (NOTA: En local NO usamos SSL, por eso no están aquí esas líneas)

# ==============================================================
#  CONFIGURACIONES GLOBALES (Aplican para Local y Producción)
# ==============================================================
# CORRECCIÓN DEFINITIVA DE HORA (Salto de 5 horas)
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'America/Lima'

# ==============================================================
#  OPTIMIZACIÓN: PLAN HOBBY RAILWAY (ACTUALIZADO)
# ==============================================================
# 1. COMPRESIÓN GZIP (Acelera la red, los JSON pesarán 80% menos)
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024

# 2. LÍMITE DE CONEXIONES HIKARI (Ajustado para Producción/Pago)
# Aumentado a 15 para soportar mayor concurrencia sin bloquear a los cajeros
spring.datasource.hikari.maximum-pool-size=5
# Mantener 5 conexiones siempre listas y vivas para responder rápido
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

# 3. PREVENCIÓN DE SATURACIÓN N+1 EN REPORTES (Hibernate Batching)
spring.jpa.properties.hibernate.default_batch_fetch_size=30

# ==============================================================
#  HIBERNATE & JPA
# ==============================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
# JAMÁS cambiar a update/create en producción
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# FORZAR HORA PERÚ EN HIBERNATE (Para fechas Java)
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

# Estrategia de nombres (VITAL para tus tablas con Mayúsculas)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ---> CONFIGURACIÓN DEL NUEVO ESQUEMA PARA JPA <---
spring.jpa.properties.hibernate.default_schema=cliente2

# ==============================================================
#  SERVIDOR Y ARRANQUE
# ==============================================================
spring.jmx.enabled=false
spring.main.lazy-initialization=false
server.port=${PORT:8080}
